# Generated by Django 5.2.13 on 2026-04-09 20:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
        ("positions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="departments.department",
                verbose_name="Отдел",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="has_transport",
            field=models.BooleanField(default=False, verbose_name="Наличие транспорта"),
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Отчество"),
        ),
        migrations.AddField(
            model_name="user",
            name="passport_issued_by",
            field=models.TextField(blank=True, verbose_name="Кем выдан"),
        ),
        migrations.AddField(
            model_name="user",
            name="passport_issued_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
        ),
        migrations.AddField(
            model_name="user",
            name="passport_number",
            field=models.CharField(
                blank=True, max_length=6, verbose_name="Номер паспорта"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="passport_series",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Серия паспорта"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="positions.position",
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram",
            field=models.CharField(blank=True, max_length=100, verbose_name="Telegram"),
        ),
        migrations.AddField(
            model_name="user",
            name="transport_description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Описание транспорта"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=100, verbose_name="WhatsApp"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
