# Generated by Django 5.2.13 on 2026-04-09 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("users", "0002_user_comment_user_created_at_user_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gallery.image",
            ),
        ),
    ]
