# Generated by Django 5.2.13 on 2026-04-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("banks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("client", "Клиент"),
                            ("partner", "Партнер"),
                            ("supplier", "Поставщик"),
                        ],
                        default="client",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "legal_address",
                    models.TextField(blank=True, verbose_name="Юридический адрес"),
                ),
                (
                    "actual_address",
                    models.TextField(blank=True, verbose_name="Фактический адрес"),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
                ),
                (
                    "ogrn",
                    models.CharField(blank=True, max_length=15, verbose_name="ОГРН"),
                ),
                ("kpp", models.CharField(blank=True, max_length=9, verbose_name="КПП")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CounterpartyBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(max_length=20, verbose_name="Расчетный счет"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Основной счет"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counterparty_accounts",
                        to="banks.bank",
                        verbose_name="Банк",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="counterparties.counterparty",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банковский счет контрагента",
                "verbose_name_plural": "Банковские счета контрагентов",
                "ordering": ["-is_primary", "bank__name"],
                "unique_together": {("counterparty", "bank", "account_number")},
            },
        ),
    ]
