# Generated by Django 5.2.13 on 2026-04-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64, verbose_name="Хеш файла"),
        ),
    ]
