# Generated by Django 5.2.13 on 2026-04-09 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("departments", "0002_department_actual_address_department_head_and_more"),
        ("gallery", "0001_initial"),
        ("manufacturers", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "article",
                    models.CharField(blank=True, max_length=50, verbose_name="Артикул"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Серийный номер"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "шт."),
                            ("kg", "кг"),
                            ("m", "м"),
                            ("l", "л"),
                            ("pack", "упак."),
                            ("set", "компл."),
                        ],
                        default="pcs",
                        max_length=10,
                        verbose_name="Ед. изм.",
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Мин. остаток",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена закупочная",
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена розничная",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_items",
                        to="categories.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_items",
                        to="departments.department",
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="warehouse_items",
                        to="gallery.image",
                        verbose_name="Изображения",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_items",
                        to="manufacturers.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Складская позиция",
                "verbose_name_plural": "Складские позиции",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("in", "Поступление"),
                            ("out", "Списание"),
                            ("move", "Перемещение между отделами"),
                            ("reserve", "Резервирование под задачу"),
                            ("return", "Возврат"),
                        ],
                        max_length=10,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Количество"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата операции"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Провел операцию",
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_transactions",
                        to="departments.department",
                        verbose_name="Отдел-отправитель",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="warehouse.warehouseitem",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_transactions",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_transactions",
                        to="departments.department",
                        verbose_name="Отдел-получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция по складу",
                "verbose_name_plural": "Журнал операций по складу",
                "ordering": ["-created_at"],
            },
        ),
    ]
