# Generated by Django 5.2.13 on 2026-04-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
        ("warehouse_locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseitem",
            name="cell",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="warehouse_locations.warehousecell",
                verbose_name="Место хранения (ячейка)",
            ),
        ),
    ]
