# Generated by Django 5.2.13 on 2026-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Наименование банка"),
                ),
                (
                    "bik",
                    models.CharField(max_length=9, unique=True, verbose_name="БИК"),
                ),
                (
                    "correspondent_account",
                    models.CharField(
                        max_length=20, verbose_name="Корреспондентский счет"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Банк",
                "verbose_name_plural": "Банки",
                "ordering": ["name"],
            },
        ),
    ]
