# Generated by Django 5.2.13 on 2026-04-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="actual_address",
            field=models.TextField(blank=True, verbose_name="Фактический адрес"),
        ),
        migrations.AddField(
            model_name="bank",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="bank",
            name="inn",
            field=models.CharField(blank=True, max_length=12, verbose_name="ИНН банка"),
        ),
        migrations.AddField(
            model_name="bank",
            name="kpp",
            field=models.CharField(blank=True, max_length=9, verbose_name="КПП банка"),
        ),
        migrations.AddField(
            model_name="bank",
            name="legal_address",
            field=models.TextField(blank=True, verbose_name="Юридический адрес"),
        ),
        migrations.AddField(
            model_name="bank",
            name="ogrn",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="ОГРН банка"
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
        ),
        migrations.AddField(
            model_name="bank",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Краткое наименование"
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="swift",
            field=models.CharField(blank=True, max_length=11, verbose_name="SWIFT-код"),
        ),
        migrations.AddField(
            model_name="bank",
            name="website",
            field=models.URLField(blank=True, verbose_name="Сайт"),
        ),
    ]
