# Generated by Django 5.2.13 on 2026-04-09 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0002_department_actual_address_department_head_and_more"),
        ("gallery", "0001_initial"),
        ("manufacturers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Серийный номер"
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Инвентарный номер"
                    ),
                ),
                (
                    "production_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата производства"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата приобретения"
                    ),
                ),
                (
                    "receipt_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата поступления на склад"
                    ),
                ),
                (
                    "decommission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата списания"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена закупочная",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("repair", "В ремонте"),
                            ("decommissioned", "Списан"),
                            ("lost", "Утерян"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "decommission_reason",
                    models.TextField(blank=True, verbose_name="Причина списания"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_items",
                        to="departments.department",
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inventory_items",
                        to="gallery.image",
                        verbose_name="Изображения",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_items",
                        to="manufacturers.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_inventory",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвентарь",
                "verbose_name_plural": "Инвентарь",
                "ordering": ["-created_at"],
            },
        ),
    ]
