# Generated by Django 5.2.13 on 2026-04-10 16:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0002_department_actual_address_department_head_and_more"),
        ("inventory", "0002_inventoryitem_category"),
        ("tasks", "0002_initial"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер документа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "Ожидает одобрения"),
                            ("approved", "Одобрено"),
                            ("issued", "Выдано"),
                            ("returned", "Возвращено"),
                            ("closed", "Закрыто"),
                            ("cancelled", "Отменено"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Дата выдачи")),
                (
                    "return_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата возврата"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_inventory_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Одобрил",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inventory_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_issues",
                        to="departments.department",
                        verbose_name="Отдел-получатель",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_inventory_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Выдал",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_issues",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Накладная на инвентарь",
                "verbose_name_plural": "Накладные на инвентарь",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_approve_inventoryissue", "Может одобрять выдачу инвентаря"),
                    ("can_issue_inventoryissue", "Может выдавать инвентарь"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryIssueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "returned",
                    models.BooleanField(default=False, verbose_name="Возвращено"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Примечание"
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_items",
                        to="inventory.inventoryitem",
                        verbose_name="Инвентарь",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.inventoryissue",
                        verbose_name="Накладная",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_inventory_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка накладной",
                "verbose_name_plural": "Строки накладной",
            },
        ),
        migrations.CreateModel(
            name="MaterialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер документа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "Ожидает одобрения"),
                            ("approved", "Одобрено"),
                            ("issued", "Выдано"),
                            ("partially_issued", "Частично выдано"),
                            ("closed", "Закрыто"),
                            ("cancelled", "Отменено"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("requested_date", models.DateField(verbose_name="Дата требования")),
                (
                    "issued_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_material_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Одобрил",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_material_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_requests",
                        to="departments.department",
                        verbose_name="Отдел-получатель",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_material_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Выдал",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_requests",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Требование-накладная",
                "verbose_name_plural": "Требования-накладные",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_approve_materialrequest", "Может одобрять требования"),
                    ("can_issue_materialrequest", "Может выдавать материалы"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Запрошено",
                    ),
                ),
                (
                    "issued_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Выдано",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Примечание"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.materialrequest",
                        verbose_name="Требование",
                    ),
                ),
                (
                    "warehouse_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_request_items",
                        to="warehouse.warehouseitem",
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка требования",
                "verbose_name_plural": "Строки требования",
                "unique_together": {("request", "warehouse_item")},
            },
        ),
    ]
