# Generated by Django 5.2.13 on 2026-04-11 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_department_actual_address_department_head_and_more"),
        ("documents", "0004_warehousetransfer_warehousetransferitem"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseStocktake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер документа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("conducted", "Проведена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "stocktake_date",
                    models.DateField(verbose_name="Дата инвентаризации"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "conducted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_stocktakes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Провёл",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_stocktakes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocktakes",
                        to="departments.department",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвентаризация",
                "verbose_name_plural": "Инвентаризации",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseStocktakeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Учётное количество",
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Фактическое количество",
                    ),
                ),
                (
                    "stocktake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.warehousestocktake",
                        verbose_name="Инвентаризация",
                    ),
                ),
                (
                    "warehouse_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocktake_items",
                        to="warehouse.warehouseitem",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка инвентаризации",
                "verbose_name_plural": "Строки инвентаризации",
            },
        ),
    ]
