# Generated by Django 5.2.13 on 2026-04-12 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_department_actual_address_department_head_and_more"),
        ("documents", "0006_inventorywriteoff_inventorywriteoffitem"),
        ("inventory", "0002_inventoryitem_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер документа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("conducted", "Проведён"),
                            ("cancelled", "Отменён"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("transfer_date", models.DateField(verbose_name="Дата перемещения")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "conducted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_inventory_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Провёл",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inventory_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_inventory_transfers",
                        to="departments.department",
                        verbose_name="Отдел-отправитель",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_inventory_transfers",
                        to="departments.department",
                        verbose_name="Отдел-получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перемещение ОС",
                "verbose_name_plural": "Перемещения ОС",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_items",
                        to="inventory.inventoryitem",
                        verbose_name="Инвентарь",
                    ),
                ),
                (
                    "new_responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_inventory",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Новый ответственный",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.inventorytransfer",
                        verbose_name="Перемещение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка перемещения ОС",
                "verbose_name_plural": "Строки перемещения ОС",
            },
        ),
    ]
