# Generated by Django 5.2.13 on 2026-04-12 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_department_actual_address_department_head_and_more"),
        ("documents", "0007_inventorytransfer_inventorytransferitem"),
        ("inventory", "0002_inventoryitem_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryStocktake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер документа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("conducted", "Проведена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "stocktake_date",
                    models.DateField(verbose_name="Дата инвентаризации"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "conducted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_inventory_stocktakes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Провёл",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inventory_stocktakes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_stocktakes",
                        to="departments.department",
                        verbose_name="Отдел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвентаризация ОС",
                "verbose_name_plural": "Инвентаризации ОС",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryStocktakeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Учётное количество"
                    ),
                ),
                (
                    "actual_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Фактическое количество"
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocktake_items",
                        to="inventory.inventoryitem",
                        verbose_name="Инвентарь",
                    ),
                ),
                (
                    "stocktake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.inventorystocktake",
                        verbose_name="Инвентаризация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка инвентаризации ОС",
                "verbose_name_plural": "Строки инвентаризации ОС",
            },
        ),
    ]
