# Generated by Django 5.2.13 on 2026-04-12 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_inventorystocktake_inventorystocktakeitem"),
        ("inventory", "0002_inventoryitem_category"),
        ("tasks", "0002_initial"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletionAct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер акта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("signed", "Подписан"),
                            ("cancelled", "Отменён"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("completion_date", models.DateField(verbose_name="Дата выполнения")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_acts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_acts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подписал",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completion_acts",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акт выполненных работ",
                "verbose_name_plural": "Акты выполненных работ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompletionActMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Фактическое количество",
                    ),
                ),
                (
                    "act",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="documents.completionact",
                    ),
                ),
                (
                    "warehouse_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.warehouseitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал акта",
                "verbose_name_plural": "Материалы акта",
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер наряда"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("issued", "Выдан"),
                            ("completed", "Выполнен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Дата выдачи")),
                (
                    "planned_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Плановое завершение"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_work_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_work_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Выдал",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Наряд на работу",
                "verbose_name_plural": "Наряды на работу",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="completionact",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completion_acts",
                to="documents.workorder",
                verbose_name="Наряд",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="documents.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвентарь наряда",
                "verbose_name_plural": "Инвентарь наряда",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Плановое количество",
                    ),
                ),
                (
                    "warehouse_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.warehouseitem",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="documents.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал наряда",
                "verbose_name_plural": "Материалы наряда",
            },
        ),
    ]
