# Generated by Django 5.2.13 on 2026-04-09 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmaterialrequirement",
            name="warehouse_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="task_requirements",
                to="warehouse.warehouseitem",
                verbose_name="Расходник",
            ),
        ),
        migrations.AddField(
            model_name="taskstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто изменил",
            ),
        ),
        migrations.AddField(
            model_name="taskstatushistory",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="tasks.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskinventoryrequirement",
            unique_together={("task", "inventory")},
        ),
        migrations.AlterUniqueTogether(
            name="taskmaterialrequirement",
            unique_together={("task", "warehouse_item")},
        ),
    ]
