# Generated by Django 5.2.13 on 2026-04-09 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="actual_address",
            field=models.TextField(blank=True, verbose_name="Фактический адрес"),
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Руководитель отдела",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="legal_address",
            field=models.TextField(blank=True, verbose_name="Юридический адрес"),
        ),
    ]
