# Generated by Django 5.2.13 on 2026-04-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_department_actual_address_department_head_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="inn",
            field=models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
        ),
        migrations.AddField(
            model_name="department",
            name="kpp",
            field=models.CharField(blank=True, max_length=9, verbose_name="КПП"),
        ),
        migrations.AddField(
            model_name="department",
            name="ogrn",
            field=models.CharField(blank=True, max_length=15, verbose_name="ОГРН"),
        ),
    ]
