# Generated by Django 5.2.13 on 2026-04-27 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0002_bank_actual_address_bank_email_bank_inn_bank_kpp_and_more"),
        ("departments", "0003_department_inn_department_kpp_department_ogrn"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="banks.bank",
                verbose_name="Банк",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Расчётный счёт"
            ),
        ),
    ]
