# Generated by Django 5.2.13 on 2026-04-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehousecell",
            name="number",
            field=models.CharField(max_length=50, verbose_name="Номер ячейки"),
        ),
        migrations.AlterUniqueTogether(
            name="warehousecell",
            unique_together={("rack", "number")},
        ),
    ]
